name: Build & Release

on:
  push:
    tags:
      - 'v*' # 当一个 'v' 开头的 tag 被推送到仓库时触发

jobs:
  release:
    runs-on: ${{ matrix.os }} # 使用矩阵策略在不同操作系统上运行

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest] # 定义要运行的操作系统

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, needed to upload assets to release
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # If the release is a draft on GitHub.
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
